services:
  - type: web
    name: runprep-multisport
    runtime: static
    buildCommand: echo "No build"
    staticPublishPath: .
    autoDeployTrigger: commit
    headers:
      - path: /sw.js
        name: Cache-Control
        value: no-cache
      - path: /index.html
        name: Cache-Control
        value: no-cache
